export const NOTIFICATION_TYPES = {
  STYLING_REQUEST: 'STYLING_REQUEST',
  STYLIST_MATCHED: 'STYLIST_MATCHED',
  NEW_MESSAGE: 'NEW_MESSAGE',
  SESSION_ENDED: 'SESSION_ENDED',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  REVIEW_RECEIVED: 'REVIEW_RECEIVED',
  WARDROBE_SHARED: 'WARDROBE_SHARED',
  OUTFIT_SUGGESTION: 'OUTFIT_SUGGESTION',
  STYLIST_APPROVED: 'STYLIST_APPROVED',
  STYLIST_REJECTED: 'STYLIST_REJECTED',
  FRIEND_REQUEST_RECEIVED: 'FRIEND_REQUEST_RECEIVED',
  FRIEND_REQUEST_ACCEPTED: 'FRIEND_REQUEST_ACCEPTED',
} as const;
